const Redis = require('ioredis');
const crypto = require('crypto');
const logger = require('../utils/logger');

/**
 * Redis Cache Service
 * Replaces node-cache with Redis for distributed caching
 */

// ── Cache Key Constants ───────────────────────────────────────────────────────
/**
 * Standardized cache key prefixes for all cacheable resources.
 * Full keys are generated by the key-generation helpers below.
 *
 * Requirements: 5.2, 5.3, 5.4
 */
const CACHE_KEYS = {
  PRODUCTS_LIST: 'products:list',
  PRODUCTS_DETAIL: 'products:detail',
  CATEGORIES_LIST: 'categories:list',
  HOMEPAGE_FEATURED: 'homepage:featured',
};

// ── TTL Constants (seconds) ───────────────────────────────────────────────────
/**
 * Time-to-live values for each cache category.
 *
 * Requirements: 5.2, 5.3, 5.4
 */
const CACHE_TTL = {
  PRODUCTS_LIST: 3600,      // 1 hour
  PRODUCTS_DETAIL: 1800,    // 30 minutes
  CATEGORIES_LIST: 86400,   // 24 hours
  HOMEPAGE_FEATURED: 300,   // 5 minutes
};

// ── Key Generation Helpers ────────────────────────────────────────────────────

/**
 * Generate a deterministic cache key for a product listing query.
 * Filters are hashed so the key stays short regardless of filter complexity.
 *
 * @param {number|string} page    - Page number
 * @param {number|string} limit   - Items per page
 * @param {Object}        filters - Arbitrary filter object (category, brand, search, etc.)
 * @returns {string} Cache key, e.g. "products:list:1:20:a3f9c2d1"
 *
 * Requirements: 5.2
 */
function generateProductListKey(page, limit, filters = {}) {
  // Sort keys for a stable hash regardless of insertion order
  const sortedFilters = Object.keys(filters)
    .sort()
    .reduce((acc, k) => {
      if (filters[k] !== undefined && filters[k] !== null && filters[k] !== '') {
        acc[k] = filters[k];
      }
      return acc;
    }, {});

  const filtersHash = Object.keys(sortedFilters).length
    ? crypto.createHash('md5').update(JSON.stringify(sortedFilters)).digest('hex').slice(0, 8)
    : 'nofilter';

  return `${CACHE_KEYS.PRODUCTS_LIST}:${page}:${limit}:${filtersHash}`;
}

/**
 * Generate a cache key for a single product detail.
 *
 * @param {string} slug - Product slug
 * @returns {string} Cache key, e.g. "products:detail:siemens-ecg-pro"
 *
 * Requirements: 5.3
 */
function generateProductDetailKey(slug) {
  return `${CACHE_KEYS.PRODUCTS_DETAIL}:${slug}`;
}

let redisClient = null;
let isConnected = false;

// ── Cache hit / miss tracking ─────────────────────────────────────────────────
/** @type {{ hits: number; misses: number; lastReset: number }} */
let cacheStats = { hits: 0, misses: 0, lastReset: Date.now() };

/**
 * Return the current hit rate as a fraction (0-1).
 * Returns 0 when there have been no requests.
 */
function getCacheHitRate() {
  const total = cacheStats.hits + cacheStats.misses;
  return total > 0 ? cacheStats.hits / total : 0;
}

/** Reset hit/miss counters. */
function resetCacheStats() {
  cacheStats = { hits: 0, misses: 0, lastReset: Date.now() };
}

/**
 * Initialize Redis connection
 */
function initRedis() {
  if (redisClient) {
    return redisClient;
  }

  try {
    const redisHost = process.env.REDIS_HOST || 'localhost';
    const redisPort = parseInt(process.env.REDIS_PORT) || 6379;
    
    // Check if TLS should be explicitly enabled via environment variable
    // Set REDIS_TLS=false in Railway to disable TLS (Redis Cloud with non-standard port may not need TLS)
    const tlsEnabled = process.env.REDIS_TLS === 'true';
    
    const redisConfig = {
      host: redisHost,
      port: redisPort,
      password: process.env.REDIS_PASSWORD || undefined,
      db: parseInt(process.env.REDIS_DB) || 0,
      // Only use TLS if explicitly enabled
      // Redis Cloud on non-standard ports may work without TLS
      tls: tlsEnabled ? {
        rejectUnauthorized: false,
        requestCert: false,
        servername: redisHost
      } : undefined,
      retryStrategy: (times) => {
        // Stop retrying after 3 attempts
        if (times > 3) {
          logger.warn('[Redis] Max retries reached. Stopping reconnection attempts.');
          return null;
        }
        const delay = Math.min(times * 50, 2000);
        return delay;
      },
      maxRetriesPerRequest: 3,
      enableReadyCheck: true,
      lazyConnect: false,
      connectTimeout: 10000,
      enableAutoPipelining: false
    };

    redisClient = new Redis(redisConfig);

    redisClient.on('connect', () => {
      logger.info('[Redis] Connecting...');
    });

    redisClient.on('ready', () => {
      isConnected = true;
      logger.info('[Redis] Connected and ready');
    });

    redisClient.on('error', (err) => {
      isConnected = false;
      logger.error(`[Redis] Error: ${err.message}`);
    });

    redisClient.on('close', () => {
      isConnected = false;
      logger.warn('[Redis] Connection closed');
    });

    redisClient.on('reconnecting', () => {
      logger.info('[Redis] Reconnecting...');
    });

    return redisClient;
  } catch (error) {
    logger.error(`[Redis] Initialization error: ${error.message}`);
    return null;
  }
}

/**
 * Get Redis client instance
 */
function getRedisClient() {
  if (!redisClient) {
    return initRedis();
  }
  return redisClient;
}

/**
 * Check if Redis is connected
 */
function isRedisConnected() {
  return isConnected && redisClient && redisClient.status === 'ready';
}

/**
 * Set cache value
 * @param {String} key - Cache key
 * @param {*} value - Value to cache (will be JSON stringified)
 * @param {Number} ttl - Time to live in seconds (default: 300)
 */
async function set(key, value, ttl = 300) {
  try {
    if (!isRedisConnected()) {
      logger.warn('[Redis] Not connected, skipping cache set');
      return false;
    }

    const serialized = JSON.stringify(value);
    
    if (ttl > 0) {
      await redisClient.setex(key, ttl, serialized);
    } else {
      await redisClient.set(key, serialized);
    }

    logger.debug(`[Redis] Set key: ${key}, TTL: ${ttl}s`);
    return true;
  } catch (error) {
    logger.error(`[Redis] Set error for key ${key}: ${error.message}`);
    return false;
  }
}

/**
 * Get cache value
 * @param {String} key - Cache key
 * @returns {*} Cached value or null
 */
async function get(key) {
  try {
    if (!isRedisConnected()) {
      logger.warn('[Redis] Not connected, skipping cache get');
      return null;
    }

    const value = await redisClient.get(key);

    if (!value) {
      cacheStats.misses++;
      return null;
    }

    cacheStats.hits++;

    // Periodic hit-rate check every 100 requests
    const total = cacheStats.hits + cacheStats.misses;
    if (total > 0 && total % 100 === 0) {
      const hitRate = cacheStats.hits / total;
      if (hitRate < 0.70) {
        logger.warn(`[Redis] Cache hit rate below 70%: ${(hitRate * 100).toFixed(1)}%`, {
          hits: cacheStats.hits,
          misses: cacheStats.misses,
        });
      }
    }

    const deserialized = JSON.parse(value);
    logger.debug(`[Redis] Get key: ${key} - HIT`);
    return deserialized;
  } catch (error) {
    logger.error(`[Redis] Get error for key ${key}: ${error.message}`);
    return null;
  }
}

/**
 * Delete cache key
 * @param {String} key - Cache key
 */
async function del(key) {
  try {
    if (!isRedisConnected()) {
      return false;
    }

    await redisClient.del(key);
    logger.debug(`[Redis] Deleted key: ${key}`);
    return true;
  } catch (error) {
    logger.error(`[Redis] Delete error for key ${key}: ${error.message}`);
    return false;
  }
}

/**
 * Delete multiple keys matching pattern
 * @param {String} pattern - Key pattern (e.g., 'products:*')
 */
async function delPattern(pattern) {
  try {
    if (!isRedisConnected()) {
      return false;
    }

    const keys = await redisClient.keys(pattern);
    
    if (keys.length > 0) {
      await redisClient.del(...keys);
      logger.debug(`[Redis] Deleted ${keys.length} keys matching pattern: ${pattern}`);
    }

    return true;
  } catch (error) {
    logger.error(`[Redis] Delete pattern error for ${pattern}: ${error.message}`);
    return false;
  }
}

/**
 * Check if key exists
 * @param {String} key - Cache key
 * @returns {Boolean}
 */
async function exists(key) {
  try {
    if (!isRedisConnected()) {
      return false;
    }

    const result = await redisClient.exists(key);
    return result === 1;
  } catch (error) {
    logger.error(`[Redis] Exists error for key ${key}: ${error.message}`);
    return false;
  }
}

/**
 * Get TTL for key
 * @param {String} key - Cache key
 * @returns {Number} TTL in seconds, -1 if no expiry, -2 if key doesn't exist
 */
async function ttl(key) {
  try {
    if (!isRedisConnected()) {
      return -2;
    }

    return await redisClient.ttl(key);
  } catch (error) {
    logger.error(`[Redis] TTL error for key ${key}: ${error.message}`);
    return -2;
  }
}

/**
 * Flush all cache
 */
async function flushAll() {
  try {
    if (!isRedisConnected()) {
      return false;
    }

    await redisClient.flushdb();
    logger.info('[Redis] Flushed all cache');
    return true;
  } catch (error) {
    logger.error(`[Redis] Flush error: ${error.message}`);
    return false;
  }
}

/**
 * Get cache statistics
 */
async function getStats() {
  try {
    if (!isRedisConnected()) {
      return {
        connected: false,
        keys: 0,
        memory: 0
      };
    }

    const info = await redisClient.info('stats');
    const dbsize = await redisClient.dbsize();
    const memory = await redisClient.info('memory');

    return {
      connected: true,
      keys: dbsize,
      info: info,
      memory: memory
    };
  } catch (error) {
    logger.error(`[Redis] Stats error: ${error.message}`);
    return {
      connected: false,
      error: error.message
    };
  }
}

/**
 * Close Redis connection
 */
async function close() {
  try {
    if (redisClient) {
      await redisClient.quit();
      redisClient = null;
      isConnected = false;
      logger.info('[Redis] Connection closed');
    }
  } catch (error) {
    logger.error(`[Redis] Close error: ${error.message}`);
  }
}

// ── Cache Warming Functions ───────────────────────────────────────────────────

/**
 * Warm featured products cache
 * Fetches and caches featured products on server startup
 * 
 * Requirements: 5.1
 */
async function warmFeaturedProducts() {
  try {
    if (!isRedisConnected()) {
      logger.warn('[Redis] Not connected, skipping featured products cache warming');
      return false;
    }

    logger.info('[Redis] Warming featured products cache...');

    // Import Product model (lazy import to avoid circular dependencies)
    const Product = require('../models/Product');

    // Fetch featured products using aggregation for better performance
    const featuredProducts = await Product.aggregate([
      { $match: { isFeatured: true, isActive: true } },
      { $sort: { createdAt: -1 } },
      { $limit: 6 },
      {
        $lookup: {
          from: 'categories',
          localField: 'category',
          foreignField: '_id',
          as: 'category'
        }
      },
      { $unwind: { path: '$category', preserveNullAndEmptyArrays: true } },
      {
        $lookup: {
          from: 'manufacturers',
          localField: 'brand',
          foreignField: '_id',
          as: 'brand'
        }
      },
      { $unwind: { path: '$brand', preserveNullAndEmptyArrays: true } },
      {
        $project: {
          name: 1,
          price: 1,
          images: 1,
          stock: 1,
          discount: 1,
          badge: 1,
          slug: 1,
          isActive: 1,
          createdAt: 1,
          rating: 1,
          oldPrice: 1,
          sku: 1,
          'category._id': 1,
          'category.name': 1,
          'category.slug': 1,
          'brand._id': 1,
          'brand.name': 1,
          'brand.slug': 1,
          'brand.logo': 1
        }
      }
    ]);

    // Cache featured products
    const cacheKey = CACHE_KEYS.HOMEPAGE_FEATURED;
    await set(cacheKey, featuredProducts, CACHE_TTL.HOMEPAGE_FEATURED);

    logger.info(`[Redis] Warmed featured products cache: ${featuredProducts.length} products cached`);
    return true;
  } catch (error) {
    logger.error(`[Redis] Featured products cache warming error: ${error.message}`);
    return false;
  }
}

/**
 * Warm categories cache
 * Fetches and caches all active categories on server startup
 * 
 * Requirements: 5.1
 */
async function warmCategories() {
  try {
    if (!isRedisConnected()) {
      logger.warn('[Redis] Not connected, skipping categories cache warming');
      return false;
    }

    logger.info('[Redis] Warming categories cache...');

    // Import Category model (lazy import to avoid circular dependencies)
    const Category = require('../models/Category');

    // Fetch all active categories
    const categories = await Category.find({ isActive: true })
      .select('name slug description image icon productCount parentCategory')
      .sort({ name: 1 })
      .lean();

    // Cache categories list
    const cacheKey = CACHE_KEYS.CATEGORIES_LIST;
    await set(cacheKey, categories, CACHE_TTL.CATEGORIES_LIST);

    logger.info(`[Redis] Warmed categories cache: ${categories.length} categories cached`);
    return true;
  } catch (error) {
    logger.error(`[Redis] Categories cache warming error: ${error.message}`);
    return false;
  }
}

/**
 * Warm popular products cache
 * Caches the first page of products (most commonly accessed)
 * 
 * Requirements: 5.1
 */
async function warmPopularProducts() {
  try {
    if (!isRedisConnected()) {
      logger.warn('[Redis] Not connected, skipping popular products cache warming');
      return false;
    }

    logger.info('[Redis] Warming popular products cache...');

    // Import Product model
    const Product = require('../models/Product');

    // Fetch first page of active products (most commonly accessed)
    const products = await Product.aggregate([
      { $match: { isActive: true } },
      { $sort: { createdAt: -1 } },
      { $limit: 20 },
      {
        $lookup: {
          from: 'categories',
          localField: 'category',
          foreignField: '_id',
          as: 'category'
        }
      },
      { $unwind: { path: '$category', preserveNullAndEmptyArrays: true } },
      {
        $lookup: {
          from: 'manufacturers',
          localField: 'brand',
          foreignField: '_id',
          as: 'brand'
        }
      },
      { $unwind: { path: '$brand', preserveNullAndEmptyArrays: true } },
      {
        $project: {
          name: 1,
          description: 1,
          price: 1,
          images: 1,
          stock: 1,
          discount: 1,
          badge: 1,
          slug: 1,
          isActive: 1,
          createdAt: 1,
          rating: 1,
          oldPrice: 1,
          sku: 1,
          'category._id': 1,
          'category.name': 1,
          'category.slug': 1,
          'brand._id': 1,
          'brand.name': 1,
          'brand.slug': 1,
          'brand.logo': 1
        }
      }
    ]);

    // Cache first page of products
    const cacheKey = generateProductListKey(1, 20, {});
    await set(cacheKey, products, CACHE_TTL.PRODUCTS_LIST);

    logger.info(`[Redis] Warmed popular products cache: ${products.length} products cached`);
    return true;
  } catch (error) {
    logger.error(`[Redis] Popular products cache warming error: ${error.message}`);
    return false;
  }
}

/**
 * Warm the aggregated homepage payload.
 * Caches under the exact key homeController reads ('homepage:aggregated:v1'),
 * so the first visitor after a restart gets a cache HIT instead of paying
 * the full multi-query DB storm (~2s on free-tier Atlas).
 */
async function warmHomepageData() {
  try {
    if (!isRedisConnected()) {
      logger.warn('[Redis] Not connected, skipping homepage cache warming');
      return false;
    }

    logger.info('[Redis] Warming aggregated homepage cache...');

    // Lazy require to avoid a circular dependency (homeController requires redisCache)
    const { buildHomeDataPayload } = require('../controllers/homeController');
    const data = await buildHomeDataPayload();

    await set('homepage:aggregated:v1', data, 600);

    logger.info(`[Redis] Warmed homepage cache (${data.featuredProducts?.length || 0} featured, ${data.newArrivals?.length || 0} new arrivals)`);
    return true;
  } catch (error) {
    logger.error(`[Redis] Homepage cache warming error: ${error.message}`);
    return false;
  }
}

/**
 * Warm all caches on server startup
 * Calls all cache warming functions in parallel
 * 
 * Requirements: 5.1
 */
async function warmAllCaches() {
  try {
    logger.info('[Redis] Starting cache warming process...');
    const startTime = Date.now();

    // Run all cache warming functions in parallel
    const results = await Promise.allSettled([
      warmFeaturedProducts(),
      warmCategories(),
      warmPopularProducts(),
      warmHomepageData()
    ]);

    // Log results
    const successful = results.filter(r => r.status === 'fulfilled' && r.value === true).length;
    const failed = results.length - successful;
    const duration = Date.now() - startTime;

    logger.info(`[Redis] Cache warming complete: ${successful}/${results.length} successful in ${duration}ms`, {
      successful,
      failed,
      duration: `${duration}ms`
    });

    return { successful, failed, duration };
  } catch (error) {
    logger.error(`[Redis] Cache warming error: ${error.message}`);
    return { successful: 0, failed: 3, error: error.message };
  }
}

// Initialize Redis on module load
initRedis();

// ── Cache Invalidation Functions ──────────────────────────────────────────────

/**
 * Invalidate all product list caches
 * Called when products are created, updated, or deleted
 * 
 * Requirements: 5.5, 5.6
 */
async function invalidateProductList() {
  try {
    if (!isRedisConnected()) {
      logger.warn('[Redis] Not connected, skipping product list cache invalidation');
      return false;
    }

    logger.info('[Redis] Invalidating product list caches...');

    // Delete all keys matching products:list:* pattern
    const deletedCount = await delPattern('products:list:*');

    // Also invalidate featured products cache
    await del(CACHE_KEYS.HOMEPAGE_FEATURED);

    logger.info(`[Redis] Invalidated product list caches: ${deletedCount} keys deleted`);
    return true;
  } catch (error) {
    logger.error(`[Redis] Product list cache invalidation error: ${error.message}`);
    return false;
  }
}

/**
 * Invalidate specific product detail cache
 * Called when a product is updated or deleted
 * 
 * Requirements: 5.5, 5.6
 * 
 * @param {string} slug - Product slug
 */
async function invalidateProductDetail(slug) {
  try {
    if (!isRedisConnected()) {
      logger.warn('[Redis] Not connected, skipping product detail cache invalidation');
      return false;
    }

    if (!slug) {
      logger.warn('[Redis] No slug provided for product detail cache invalidation');
      return false;
    }

    logger.info(`[Redis] Invalidating product detail cache for slug: ${slug}`);

    // Delete specific product detail cache
    const cacheKey = generateProductDetailKey(slug);
    await del(cacheKey);

    logger.info(`[Redis] Invalidated product detail cache: ${cacheKey}`);
    return true;
  } catch (error) {
    logger.error(`[Redis] Product detail cache invalidation error: ${error.message}`);
    return false;
  }
}

/**
 * Invalidate all category caches
 * Called when categories are created, updated, or deleted
 * 
 * Requirements: 5.5, 5.6
 */
async function invalidateCategories() {
  try {
    if (!isRedisConnected()) {
      logger.warn('[Redis] Not connected, skipping categories cache invalidation');
      return false;
    }

    logger.info('[Redis] Invalidating categories cache...');

    // Delete categories list cache with wildcard to catch all query variations
    // This will delete: categories:list:/api/categories?includeInactive=true
    //                   categories:list:/api/categories?includeInactive=false
    //                   categories:list:/api/categories, etc.
    const categoryDeleted = await delPattern(`${CACHE_KEYS.CATEGORIES_LIST}*`);

    // Also invalidate product lists since they include category data
    const productListDeleted = await delPattern('products:list:*');

    logger.info(`[Redis] Invalidated ${categoryDeleted} category caches and ${productListDeleted} product list caches`);
    return true;
  } catch (error) {
    logger.error(`[Redis] Categories cache invalidation error: ${error.message}`);
    return false;
  }
}

/**
 * Invalidate all brand-related caches
 * Called when brands are created, updated, or deleted
 * 
 * Requirements: 5.5, 5.6
 */
async function invalidateBrands() {
  try {
    if (!isRedisConnected()) {
      logger.warn('[Redis] Not connected, skipping brands cache invalidation');
      return false;
    }

    logger.info('[Redis] Invalidating brands cache...');

    // Delete brands list cache if it exists
    await del('brands:list');

    // Also invalidate product lists since they include brand data
    const deletedCount = await delPattern('products:list:*');

    logger.info(`[Redis] Invalidated brands cache and ${deletedCount} product list caches`);
    return true;
  } catch (error) {
    logger.error(`[Redis] Brands cache invalidation error: ${error.message}`);
    return false;
  }
}

/**
 * Invalidate order-related caches for a specific user
 * Called when orders are created, updated, or deleted
 * 
 * Requirements: 5.7
 * 
 * @param {string} userId - User ID
 */
async function invalidateUserOrders(userId) {
  try {
    if (!isRedisConnected()) {
      logger.warn('[Redis] Not connected, skipping user orders cache invalidation');
      return false;
    }

    if (!userId) {
      logger.warn('[Redis] No userId provided for orders cache invalidation');
      return false;
    }

    logger.info(`[Redis] Invalidating orders cache for user: ${userId}`);

    // Delete user-specific order caches
    const deletedCount = await delPattern(`orders:user:${userId}:*`);

    logger.info(`[Redis] Invalidated user orders cache: ${deletedCount} keys deleted`);
    return true;
  } catch (error) {
    logger.error(`[Redis] User orders cache invalidation error: ${error.message}`);
    return false;
  }
}

/**
 * Invalidate all caches (nuclear option)
 * Use sparingly - only for major data migrations or system maintenance
 * 
 * Requirements: 5.7
 */
async function invalidateAllCaches() {
  try {
    if (!isRedisConnected()) {
      logger.warn('[Redis] Not connected, skipping all caches invalidation');
      return false;
    }

    logger.warn('[Redis] Invalidating ALL caches (nuclear option)...');

    // Flush all Redis keys
    await flushAll();

    logger.warn('[Redis] All caches invalidated');
    return true;
  } catch (error) {
    logger.error(`[Redis] All caches invalidation error: ${error.message}`);
    return false;
  }
}

// Graceful shutdown
process.on('SIGTERM', close);
process.on('SIGINT', close);

module.exports = {
  // Constants
  CACHE_KEYS,
  CACHE_TTL,
  // Key generation helpers
  generateProductListKey,
  generateProductDetailKey,
  // Core operations
  initRedis,
  getRedisClient,
  isRedisConnected,
  set,
  get,
  del,
  delPattern,
  exists,
  ttl,
  flushAll,
  getStats,
  close,
  // Hit-rate monitoring
  getCacheHitRate,
  resetCacheStats,
  get cacheStats() {
 return { ...cacheStats }; 
},
  // Cache warming
  warmFeaturedProducts,
  warmCategories,
  warmPopularProducts,
  warmHomepageData,
  warmAllCaches,
  // Cache invalidation
  invalidateProductList,
  invalidateProductDetail,
  invalidateCategories,
  invalidateBrands,
  invalidateUserOrders,
  invalidateAllCaches,
};
