# Nixpacks Configuration for Railway
# https://nixpacks.com/docs/configuration

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install --production=false"]

[start]
cmd = "npm start"
