services:
  - type: web
    name: mediportbd-api
    runtime: node
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
