"use client";

import { confirmAction } from '@/components/ui/ConfirmDialog';
import EmptyState from '@/components/ui/EmptyState';
import { useState, useEffect, useCallback, useRef } from 'react';
import { API } from '@/constants/api';

// ── SKU generation helpers ────────────────────────────────────────────────────
const SKU_CATEGORY_CODES = {
  'diagnostic': 'DX', 'diagnostics': 'DX', 'diagnostic equipment': 'DX',
  'surgical': 'SG', 'surgical instruments': 'SG',
  'laboratory': 'LB', 'lab equipment': 'LB', 'lab': 'LB',
  'reagent': 'RG', 'reagents': 'RG', 'laboratory reagents': 'RG',
  'hospital': 'HM', 'hospital machines': 'HM',
  'ppe': 'PP', 'ppe & safety': 'PP', 'safety': 'PP',
  'dental': 'DN', 'dental equipment': 'DN',
  'implants': 'IM', 'implants & ortho': 'IM', 'ortho': 'IM',
};

function getCategoryCode(name = '') {
  const lower = name.toLowerCase().trim();
  if (SKU_CATEGORY_CODES[lower]) return SKU_CATEGORY_CODES[lower];
  for (const [key, code] of Object.entries(SKU_CATEGORY_CODES)) {
    if (lower.includes(key) || key.includes(lower)) return code;
  }
  return name.replace(/[^A-Za-z]/g, '').substring(0, 2).toUpperCase() || 'XX';
}

function getBrandCode(name = '') {
  const words = name.replace(/[^A-Za-z\s]/g, '').trim()
    .split(/\s+/)
    .filter(w => !['the','and','of','co','ltd','inc','corp','group'].includes(w.toLowerCase()));
  return words.join('').substring(0, 3).toUpperCase() || 'GEN';
}
// ─────────────────────────────────────────────────────────────────────────────

const UNITS = ['piece', 'box', 'kit', 'pack'];
const CERTIFICATIONS = ['CE', 'FDA', 'ISO', 'DGDA'];

const EMPTY_CREATE_FORM = {
  sku: '',
  name: '',
  description: '',
  brand: '', // Will store ObjectId when selected from dropdown
  category: '', // Will store ObjectId when selected from dropdown
  subcategory: '',
  price: '',
  b2bPrice: '',
  oldPrice: '',
  discountPct: '',
  stock: '',
  lowStockThreshold: '10',
  unit: 'piece',
  minOrderQty: '1',
  certifications: [],
  specifications: [],     // array of {key, value}
  sizes: [],              // array of {name, stock, priceAdjustment, isAvailable}
  storageTemp: 'room',
  hazardClass: 'safe',
  compatibleWith: [],
  tags: [],
  lotNumber: '',
  expiryDate: '',
  hasAMC: false,
  isFeatured: false,
  isActive: true,
  images: [],          // array of uploaded URLs
};

export default function ProductsManagement({ openCreateRef }) {
  const [products, setProducts] = useState([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [categoryFilter, setCategoryFilter] = useState('');
  const [brandFilter, setBrandFilter] = useState('');
  const [statusFilter, setStatusFilter] = useState('');
  const [stockFilter, setStockFilter] = useState('');
  const [searchQuery, setSearchQuery] = useState('');
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState({ text: '', type: '' });

  // Dynamic data from API
  const [categories, setCategories] = useState([]);
  const [manufacturers, setManufacturers] = useState([]);
  const [loadingMeta, setLoadingMeta] = useState(true);

  // Edit modal state
  const [modalMode, setModalMode] = useState('create'); // 'create' | 'edit'
  const [modalProduct, setModalProduct] = useState(null); // product being edited

  // Create modal state
  const [showCreate, setShowCreate] = useState(false);
  const [createForm, setCreateForm] = useState(EMPTY_CREATE_FORM);
  const [creating, setCreating] = useState(false);

  // Brand search state
  const [brandSearch, setBrandSearch] = useState('');
  const [showBrandDropdown, setShowBrandDropdown] = useState(false);

  // SKU auto-generation state
  const [skuGenerating, setSkuGenerating] = useState(false);
  const [skuAutoGenerated, setSkuAutoGenerated] = useState(false);

  const skuGenRef = useRef(null);

  // Helper function for showing messages - moved to top to prevent access before declaration
  const showMessage = useCallback((text, type) => {
    setMessage({ text, type });
    setTimeout(() => setMessage({ text: '', type: '' }), 3000);
  }, []);

  /**
   * Build a professional client-side SKU when the backend is unreachable.
   * Format: MC-{CAT}-{BRD}-{YYYYMMDD}-{4-digit counter}
   * The counter is derived from how many products already share this prefix in
   * the loaded product list, so it never duplicates within the current session.
   */
  const buildFallbackSku = useCallback((catName, brandName) => {
    const catCode   = getCategoryCode(catName);
    const brandCode = getBrandCode(brandName);
    const prefix    = `MC-${catCode}-${brandCode}-`;
    // Count existing products that share this prefix to derive a local sequence
    const existing  = (products || []).filter(p => p.sku && p.sku.startsWith(prefix));
    const seq       = String(existing.length + 1).padStart(4, '0');
    return `${prefix}${seq}`;
  }, [products]);

  /**
   * Auto-generate SKU whenever BOTH category and brand are set (create mode only).
   * Tries the backend API first; falls back to client-side generation if it fails.
   */
  useEffect(() => {
    if (modalMode === 'edit') return;
    if (!createForm.category || !createForm.brand) return;

    if (skuGenRef.current) clearTimeout(skuGenRef.current);
    skuGenRef.current = setTimeout(async () => {
      setSkuGenerating(true);
      try {
        const token = localStorage.getItem('Mediport_token');
        const res = await fetch(
          `${API}/products/generate-sku?categoryId=${createForm.category}&brandId=${createForm.brand}`,
          { headers: { Authorization: `Bearer ${token}` } }
        );
        const data = await res.json();
        if (data.success && data.sku) {
          setCreateForm(f => ({ ...f, sku: data.sku }));
          setSkuAutoGenerated(true);
          setSkuGenerating(false);
          return;
        }
      } catch (_e) { /* fall through to client-side generation */ }

      // ── Client-side fallback ──────────────────────────────────────────────
      const cat   = (categories || []).find(c => c._id === createForm.category);
      const brand = (manufacturers || []).find(m => m._id === createForm.brand);
      if (cat && brand) {
        const sku = buildFallbackSku(cat.name, brand.name);
        setCreateForm(f => ({ ...f, sku }));
        setSkuAutoGenerated(true);
      }
      setSkuGenerating(false);
    }, 400);

    return () => { if (skuGenRef.current) clearTimeout(skuGenRef.current); };
  }, [createForm.category, createForm.brand, modalMode, categories, manufacturers, buildFallbackSku]);

  // Manual trigger for the ↺ regenerate button
  const generateSku = useCallback(async (categoryId, brandId) => {
    if (!categoryId || !brandId) return;
    setSkuGenerating(true);
    try {
      const token = localStorage.getItem('Mediport_token');
      const res = await fetch(
        `${API}/products/generate-sku?categoryId=${categoryId}&brandId=${brandId}`,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      const data = await res.json();
      if (data.success && data.sku) {
        setCreateForm(f => ({ ...f, sku: data.sku }));
        setSkuAutoGenerated(true);
        setSkuGenerating(false);
        return;
      }
    } catch (_e) { /* fall through */ }

    // Client-side fallback
    const cat   = (categories || []).find(c => c._id === categoryId);
    const brand = (manufacturers || []).find(m => m._id === brandId);
    if (cat && brand) {
      const sku = buildFallbackSku(cat.name, brand.name);
      setCreateForm(f => ({ ...f, sku }));
      setSkuAutoGenerated(true);
    }
    setSkuGenerating(false);
  }, [categories, manufacturers, buildFallbackSku]);

  // Expose open function to parent via ref
  useEffect(() => {
    if (openCreateRef) openCreateRef.current = () => setShowCreate(true);
  }, [openCreateRef]);

  // Close brand dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (e) => {
      if (showBrandDropdown && !e.target.closest('.brand-dropdown-container')) {
        setShowBrandDropdown(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [showBrandDropdown]);

  // Fetch categories and manufacturers on mount
  useEffect(() => {
    const fetchMetadata = async () => {
      try {
        setLoadingMeta(true);
        const token = localStorage.getItem('Mediport_token');
        const headers = { Authorization: `Bearer ${token}` };
        
        const [categoriesRes, manufacturersRes] = await Promise.all([
          fetch(`${API}/categories`, { headers }),
          fetch(`${API}/manufacturers`, { headers })
        ]);
        
        const categoriesData = await categoriesRes.json();
        const manufacturersData = await manufacturersRes.json();
        
        const cats = categoriesData.categories || categoriesData.data?.categories || categoriesData.data || [];
        const mfrs = manufacturersData.manufacturers || manufacturersData.data?.manufacturers || manufacturersData.data || [];
        
        // Ensure arrays are always arrays
        setCategories(Array.isArray(cats) ? cats : []);
        setManufacturers(Array.isArray(mfrs) ? mfrs : []);
      } catch (err) {
        showMessage('Failed to load categories/manufacturers', 'error');
      } finally {
        setLoadingMeta(false);
      }
    };
    fetchMetadata();
  }, [showMessage]);

  // Fetch products when filters change - inlined to avoid setState-in-effect ESLint error
  useEffect(() => { 
    const fetchProducts = async () => {
      try {
        setLoading(true);
        const filters = { page, limit: 20 };
        if (categoryFilter) filters.category = categoryFilter;
        if (brandFilter) filters.brand = brandFilter;
        if (searchQuery) filters.search = searchQuery;
        if (statusFilter) {
          if (statusFilter === 'active') filters.isActive = 'true';
          if (statusFilter === 'inactive') filters.isActive = 'false';
          if (statusFilter === 'featured') filters.isFeatured = 'true';
        }
        if (stockFilter) {
          if (stockFilter === 'instock') filters.inStock = 'true';
          if (stockFilter === 'lowstock') filters.lowStock = 'true';
          if (stockFilter === 'outofstock') filters.outOfStock = 'true';
        }
        // Add cache buster to force fresh data
        filters._t = Date.now().toString();
        
        // Use the API helper which includes auth headers
        const token = localStorage.getItem('Mediport_token');
        
        const url = `${API}/products?${new URLSearchParams(filters)}`;
        
        const res = await fetch(url, {
          headers: { 
            Authorization: `Bearer ${token}`,
            'Cache-Control': 'no-cache',
            'Pragma': 'no-cache'
          },
          cache: 'no-store'
        });
        
        const data = await res.json();
        
        // API returns: { success, data: [...products...], pagination }
        // where data is the products array directly
        let productsArray = [];
        if (Array.isArray(data.data)) {
          productsArray = data.data;
        } else if (data.data?.products) {
          productsArray = data.data.products;
        } else if (data.products) {
          productsArray = data.products;
        }
        
        setProducts(Array.isArray(productsArray) ? productsArray : []);
        setTotal(data.pagination?.total || data.total || data.data?.total || 0);
      } catch (error) {
        showMessage('Failed to load products', 'error');
      } finally {
        setLoading(false);
      }
    };
    
    fetchProducts();
  }, [page, categoryFilter, brandFilter, statusFilter, stockFilter, searchQuery, showMessage]);

  // Keep fetchProducts as a separate function for manual refresh (delete, create, edit)
  const fetchProducts = useCallback(async () => {
    try {
      setLoading(true);
      const filters = { page, limit: 20 };
      if (categoryFilter) filters.category = categoryFilter;
      if (brandFilter) filters.brand = brandFilter;
      if (searchQuery) filters.search = searchQuery;
      if (statusFilter) {
        if (statusFilter === 'active') filters.isActive = 'true';
        if (statusFilter === 'inactive') filters.isActive = 'false';
        if (statusFilter === 'featured') filters.isFeatured = 'true';
      }
      if (stockFilter) {
        if (stockFilter === 'instock') filters.inStock = 'true';
        if (stockFilter === 'lowstock') filters.lowStock = 'true';
        if (stockFilter === 'outofstock') filters.outOfStock = 'true';
      }
      // Add cache buster to force fresh data
      filters._t = Date.now().toString();
      
      // Use the API helper which includes auth headers
      const token = localStorage.getItem('Mediport_token');
      
      const url = `${API}/products?${new URLSearchParams(filters)}`;
      
      const res = await fetch(url, {
        headers: { 
          Authorization: `Bearer ${token}`,
          'Cache-Control': 'no-cache',
          'Pragma': 'no-cache'
        },
        cache: 'no-store'
      });
      
      const data = await res.json();
      
      // API returns: { success, data: [...products...], pagination }
      // where data is the products array directly
      let productsArray = [];
      if (Array.isArray(data.data)) {
        productsArray = data.data;
      } else if (data.data?.products) {
        productsArray = data.data.products;
      } else if (data.products) {
        productsArray = data.products;
      }
      
      setProducts(Array.isArray(productsArray) ? productsArray : []);
      setTotal(data.pagination?.total || data.total || data.data?.total || 0);
    } catch (error) {
      showMessage('Failed to load products', 'error');
    } finally {
      setLoading(false);
    }
  }, [page, categoryFilter, brandFilter, statusFilter, stockFilter, searchQuery, showMessage]);

  const handleDelete = async (productId) => {
    if (!await confirmAction('Delete this product? This cannot be undone.')) return;
    try {
      const token = localStorage.getItem('Mediport_token');
      const res = await fetch(`${API}/products/${productId}`, {
        method: 'DELETE',
        headers: { Authorization: `Bearer ${token}` }
      });
      if (!res.ok) throw new Error('Delete failed');
      showMessage('Product deleted', 'success');
      fetchProducts();
    } catch {
      showMessage('Failed to delete product', 'error');
    }
  };

  const handleEditOpen = (product) => {
    try {
      setModalMode('edit');
      setModalProduct(product);
      
      // Extract IDs from populated fields (handle both string and ObjectId formats)
      const categoryId = product.category && typeof product.category === 'object' ? product.category._id : product.category;
      const brandId = product.brand && typeof product.brand === 'object' ? product.brand._id : product.brand;
      
      // Pre-fill createForm with all product fields
      const formData = {
        name:              product.name || '',
        sku:               product.sku || '',
        brand:             brandId || '',
        category:          categoryId || '',
        subcategory:       product.subcategory || '',
        description:       product.description || '',
        price:             product.price?.toString() || '',
        b2bPrice:          product.b2bPrice?.toString() || '',
        oldPrice:          product.oldPrice?.toString() || '',
        discountPct:       product.discountPct?.toString() || '0',
        stock:             product.stock?.toString() || '',
        lowStockThreshold: product.lowStockThreshold?.toString() || '10',
        unit:              product.unit || 'piece',
        minOrderQty:       product.minOrderQty?.toString() || '1',
        certifications:    product.certifications || [],
        specifications:    product.specifications && typeof product.specifications === 'object'
                           ? Object.entries(product.specifications).map(([key, value]) => ({ key: String(key), value: String(value) }))
                           : [],
        storageTemp:       product.storageTemp || 'room',
        hazardClass:       product.hazardClass || 'safe',
        compatibleWith:    product.compatibleWith || [],
        tags:              product.tags || [],
        lotNumber:         product.lotNumber || '',
        expiryDate:        product.expiryDate ? product.expiryDate.split('T')[0] : '',
        hasAMC:            product.hasAMC || false,
        isFeatured:        product.isFeatured || false,
        isActive:          product.isActive !== false,
        images:            product.images || [],
      };
      
      setCreateForm(formData);
      
      // Set brand search to display name
      if (typeof product.brand === 'object' && product.brand?.name) {
        setBrandSearch(product.brand.name);
      } else if (typeof product.brand === 'string') {
        // Legacy string brand - find matching manufacturer
        const manufacturer = manufacturers?.find(m => m._id === product.brand || m.name === product.brand);
        setBrandSearch(manufacturer?.name || product.brand);
      } else {
        setBrandSearch('');
      }
      
      setShowCreate(true); // reuse the same modal
    } catch (error) {
      if (process.env.NODE_ENV !== "production") console.error('Error opening edit modal:', error);
      showMessage('Failed to open edit form', 'error');
    }
  };

  const handleEditSave = async () => {
    if (!modalProduct) return;
    setCreating(true);
    try {
      const token = localStorage.getItem('Mediport_token');
      const payload = {
        ...createForm,
        price: Number(createForm.price),
        stock: Number(createForm.stock),
        lowStockThreshold: Number(createForm.lowStockThreshold) || 10,
        minOrderQty: Number(createForm.minOrderQty) || 1,
        ...(createForm.b2bPrice ? { b2bPrice: Number(createForm.b2bPrice) } : {}),
        ...(createForm.oldPrice ? { oldPrice: Number(createForm.oldPrice) } : {}),
        ...(createForm.discountPct ? { discountPct: Number(createForm.discountPct) } : {}),
      };
      
      const res = await fetch(`${API}/products/${modalProduct._id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify(payload)
      });
      
      if (!res.ok) {
        const errorData = await res.json();
        throw new Error(errorData.message || 'Update failed');
      }
      
      const result = await res.json();
      
      showMessage('Product updated successfully', 'success');
      closeModal();
      
      // Force refresh the products list
      await fetchProducts();
    } catch (error) {
      showMessage(error.message || 'Failed to update product', 'error');
    } finally {
      setCreating(false);
    }
  };

  const closeModal = () => {
    setShowCreate(false);
    setCreateForm(EMPTY_CREATE_FORM);
    setModalMode('create');
    setModalProduct(null);
    setBrandSearch('');
    setShowBrandDropdown(false);
    setSkuAutoGenerated(false);
  };

  // ── Image upload (via Backend API) ─────────────────────────────────────────
  const [uploading, setUploading] = useState(false);
  
  const handleFileUpload = async (e) => {
    const files = Array.from(e.target.files || []);
    if (files.length === 0) return;
    
    if (createForm.images.length + files.length > 5) {
      showMessage('Maximum 5 images per product', 'error');
      return;
    }
    
    setUploading(true);
    let uploaded = 0;
    let failed = 0;
    
    try {
      for (const file of files) {
        // Validate file type
        if (!['image/jpeg', 'image/jpg', 'image/png', 'image/webp'].includes(file.type)) {
          showMessage(`Invalid file type: ${file.name}. Only JPEG, PNG, WebP allowed.`, 'error');
          failed++;
          continue;
        }
        
        // Validate file size (5MB)
        if (file.size > 5 * 1024 * 1024) {
          showMessage(`File too large: ${file.name}. Max 5MB.`, 'error');
          failed++;
          continue;
        }
        
        const formData = new FormData();
        formData.append('image', file);
        
        const response = await fetch(`${API}/upload/image`, {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${localStorage.getItem('Mediport_token')}`,
          },
          body: formData,
        });
        
        const data = await response.json();
        
        if (data.success && (data.data?.url || data.url)) {
          const imageUrl = data.data?.url || data.url;
          const imagePublicId = data.data?.publicId || data.publicId || '';
          
          setCreateForm(f => {
            const newImage = {
              url: imageUrl,
              publicId: imagePublicId,
              isPrimary: f.images.length === 0,
              alt: f.name || 'Product image',
            };
            return { ...f, images: [...f.images, newImage] };
          });
          uploaded++;
        } else {
          showMessage(data.message || 'Upload failed', 'error');
          failed++;
        }
      }
      
      if (uploaded > 0 && failed === 0) {
        showMessage(`${uploaded} image${uploaded > 1 ? 's' : ''} uploaded`, 'success');
      } else if (uploaded > 0 && failed > 0) {
        showMessage(`${uploaded} uploaded, ${failed} failed`, 'success');
      } else if (failed > 0) {
        showMessage(`Upload failed`, 'error');
      }
    } catch (error) {
      showMessage('Upload failed. Please try again.', 'error');
    } finally {
      setUploading(false);
      e.target.value = '';
    }
  };

  const handleRemoveImage = (idx) => {
    setCreateForm(f => {
      const updated = f.images.filter((_, i) => i !== idx);
      // If deleted was primary, make first remaining primary
      if (f.images[idx]?.isPrimary && updated.length > 0) {
        updated[0].isPrimary = true;
      }
      return { ...f, images: updated };
    });
  };

  // ── Create/Edit product ──────────────────────────────────────────────────────
  const handleCreateProduct = async () => {
    // Basic validation
    if (!createForm.sku.trim()) return showMessage('SKU is required', 'error');
    if (!createForm.name.trim()) return showMessage('Product name is required', 'error');
    if (!createForm.description.trim()) return showMessage('Description is required', 'error');
    if (!createForm.brand) return showMessage('Brand is required', 'error');
    if (!createForm.category) return showMessage('Category is required', 'error');
    if (!createForm.price || isNaN(Number(createForm.price))) return showMessage('Valid price is required', 'error');
    if (createForm.stock === '' || isNaN(Number(createForm.stock))) return showMessage('Valid stock quantity is required', 'error');
    
    // Reagent validation
    const selectedCategory = categories?.find(c => c._id === createForm.category);

    setCreating(true);
    try {
      const token = localStorage.getItem('Mediport_token');
      const url = modalMode === 'edit' ? `${API}/products/${modalProduct._id}` : `${API}/products`;
      const method = modalMode === 'edit' ? 'PUT' : 'POST';
      
      // Auto-calculate B2B price if not provided
      const retailPrice = Number(createForm.price);
      const calculatedB2bPrice = createForm.b2bPrice 
        ? Number(createForm.b2bPrice) 
        : Math.round(retailPrice * 0.78);
      
      // Convert specifications array [{key, value}] → plain object for the API
      const specificationsObj = {};
      (createForm.specifications || []).forEach(({ key, value }) => {
        if (key && key.trim() && value && value.trim()) {
          specificationsObj[key.trim()] = value.trim();
        }
      });

      // Strip internal UI-only fields before sending to the API
      const { tagInput, compatibleInput, ...formFields } = createForm;
      
      // Prepare size variants if they exist
      const variants = {};
      if (createForm.sizes && createForm.sizes.length > 0) {
        const validSizes = createForm.sizes.filter(s => s.name && s.name.trim());
        if (validSizes.length > 0) {
          variants.sizes = validSizes.map(s => ({
            name: s.name,
            sku: `${createForm.sku}-${s.name}`,
            stock: Number(s.stock) || 0,
            priceAdjustment: Number(s.priceAdjustment) || 0,
            isAvailable: s.isAvailable !== false
          }));
        }
      }
      
      const payload = {
        ...formFields,
        price: retailPrice,
        b2bPrice: calculatedB2bPrice,
        stock: Number(createForm.stock),
        lowStockThreshold: Number(createForm.lowStockThreshold) || 10,
        minOrderQty: Number(createForm.minOrderQty) || 1,
        specifications: specificationsObj,
        ...(Object.keys(variants).length > 0 ? { variants } : {}),
        ...(createForm.oldPrice ? { oldPrice: Number(createForm.oldPrice) } : { oldPrice: undefined }),
        ...(createForm.discountPct ? { discountPct: Number(createForm.discountPct) } : {}),
        ...(createForm.expiryDate ? { expiryDate: createForm.expiryDate } : {}),
      };
      const res = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify(payload),
      });
      const data = await res.json();
      if (!res.ok || !data.success) {
        // Show the specific field errors if the backend returns them
        if (data.errors && Array.isArray(data.errors) && data.errors.length > 0) {
          const errorDetails = data.errors.map(e => `${e.field}: ${e.message}`).join(' · ');
          throw new Error(errorDetails);
        }
        throw new Error(data.message || `${modalMode === 'edit' ? 'Update' : 'Create'} failed`);
      }
      showMessage(modalMode === 'edit' ? 'Product updated successfully' : 'Product created successfully', 'success');
      closeModal();
      fetchProducts();
    } catch (err) {
      showMessage(err.message || `Failed to ${modalMode === 'edit' ? 'update' : 'create'} product`, 'error');
    } finally {
      setCreating(false);
    }
  };

  const getStockStatus = (product) => {
    if (product.stock === 0) return { color: 'bg-[var(--color-status-danger-tint)] text-[var(--color-status-danger)]', label: 'Out of stock' };
    if (product.stock <= (product.lowStockThreshold || 10)) return { color: 'bg-[var(--color-status-warning-tint)] text-[var(--color-status-warning)]', label: 'Low stock' };
    return { color: 'bg-[var(--color-status-success-tint)] text-[var(--color-status-success)]', label: 'In stock' };
  };

  const totalPages = Math.ceil(total / 20);

  return (
    <div className="bg-white rounded-lg border-[0.5px] border-[var(--color-border-tertiary)] overflow-hidden">
      {/* Message Toast */}
      {message.text && (
        <div className={`fixed top-4 right-4 px-4 py-3 rounded-lg shadow-lg z-toast ${
          message.type === 'success' ? 'bg-[var(--color-status-success-tint)] text-[var(--color-status-success)]' : 'bg-[var(--color-status-danger-tint)] text-[var(--color-status-danger)]'
        }`}>
          {message.text}
        </div>
      )}

      {/* ── Create Product Modal ─────────────────────────────────────────── */}
      {showCreate && (
        <div className="fixed inset-0 bg-black/50 flex items-end sm:items-start justify-center z-modal overflow-y-auto sm:py-8 sm:px-4">
          <div className="bg-white rounded-t-lg sm:rounded-xl w-full max-w-2xl shadow-lg max-h-[95vh] sm:max-h-none overflow-y-auto">
            {/* Header */}
            <div className="flex items-center justify-between px-4 sm:px-6 py-4 border-b-[0.5px] border-[var(--color-border-tertiary)] sticky top-0 bg-white z-10">
              <h3 className="text-base font-semibold font-[family-name:var(--font-plus-jakarta)]">
                {modalMode === 'edit' ? `Edit — ${modalProduct?.name}` : 'Add New Product'}
              </h3>
              <button
                onClick={closeModal}
                className="w-10 h-10 flex items-center justify-center rounded-full text-[var(--color-text-secondary)] hover:text-[var(--color-text-primary)] hover:bg-[var(--color-background-secondary)] text-xl leading-none transition-colors"
                aria-label="Close"
              >
                ×
              </button>
            </div>

            <div className="px-4 sm:px-6 py-5 space-y-5">
              {/* Image Upload */}
              <div>
                <label className="block text-sm font-semibold text-[var(--color-text-primary)] mb-2">
                  Product Images <span className="font-normal text-[var(--color-text-secondary)]">(up to 5 — JPEG, PNG, WebP)</span>
                </label>

                <label
                  htmlFor="image-upload"
                  className={`w-full border-2 border-dashed border-[var(--color-border-secondary)] hover:border-brand-teal hover:bg-[var(--color-status-success-tint)] rounded-lg p-5 text-center transition-colors cursor-pointer block ${uploading ? 'opacity-50 pointer-events-none' : ''}`}
                >
                  <input
                    id="image-upload"
                    type="file"
                    accept="image/jpeg,image/jpg,image/png,image/webp"
                    multiple
                    onChange={handleFileUpload}
                    disabled={uploading || createForm.images.length >= 5}
                    className="hidden"
                  />
                  <svg className="mx-auto mb-2 w-8 h-8 text-[var(--color-text-secondary)]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                  </svg>
                  <p className="text-xs text-[var(--color-text-secondary)]">
                    {uploading ? 'Uploading...' : 'Click to upload images'}
                    {createForm.images.length > 0 && !uploading && (
                      <span className="ml-1 text-brand-teal font-medium">({createForm.images.length}/5 added)</span>
                    )}
                  </p>
                  <p className="text-xs text-[var(--color-text-secondary)] mt-1">JPEG, PNG, WebP — max 5 MB each</p>
                </label>

                {/* Image previews */}
                {createForm.images.length > 0 && (
                  <div className="flex flex-wrap gap-2 mt-3">
                    {createForm.images.map((img, idx) => (
                      <div 
                        key={img.publicId || img.url || idx} 
                        className="relative group w-20 h-20 rounded-lg overflow-hidden cursor-pointer"
                        style={{
                          border: img.isPrimary ? '2px solid var(--color-brand-teal)' : '0.5px solid var(--color-border-primary)'
                        }}
                        onClick={() => {
                          // Set clicked image as primary
                          const updated = createForm.images.map((image, i) => ({
                            ...image,
                            isPrimary: i === idx,
                          }));
                          setCreateForm(f => ({ ...f, images: updated }));
                        }}
                        title="Click to set as primary image"
                      >
                        {/* eslint-disable-next-line @next/next/no-img-element */}
                        <img src={img.url} alt={`Product image ${idx + 1}`} className="w-full h-full object-cover" loading="lazy" />
                        
                        {/* Primary badge */}
                        {img.isPrimary && (
                          <div className="absolute bottom-0 left-0 right-0 bg-brand-teal text-white text-xs text-center py-[2px] font-semibold" style={{ background: 'rgba(14,138,110,0.9)' }}>
                            PRIMARY
                          </div>
                        )}
                        
                        {/* Delete button */}
                        <button
                          type="button"
                          onClick={(e) => {
                            e.stopPropagation(); // don't trigger primary selection
                            handleRemoveImage(idx);
                          }}
                          className="absolute top-1 right-1 w-5 h-5 rounded-full flex items-center justify-center text-white text-sm opacity-0 group-hover:opacity-100 transition-opacity"
                          style={{ background: 'rgba(226,75,74,0.9)' }}
                          aria-label="Remove image"
                        >
                          ×
                        </button>
                      </div>
                    ))}
                  </div>
                )}
                {createForm.images.length > 0 && (
                  <div className="text-xs text-[var(--color-text-tertiary)] mt-2">
                    Click any image to set as primary · Hover and click × to remove
                  </div>
                )}
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm text-[var(--color-text-secondary)] mb-1 flex items-center gap-1.5">
                    SKU <span className="text-[var(--color-status-danger)]">*</span>
                    {skuAutoGenerated && modalMode === 'create' && (
                      <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-xs font-semibold bg-[var(--color-status-success-tint)] text-brand-teal border border-[#A7F3D0]">
                        <svg width="8" height="8" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3"><polyline points="20 6 9 17 4 12"/></svg>
                        AUTO
                      </span>
                    )}
                  </label>
                  <div className="relative">
                    <input
                      type="text"
                      placeholder={
                        skuGenerating
                          ? 'Generating…'
                          : createForm.category && createForm.brand
                          ? 'Generating SKU…'
                          : 'Select category & brand first'
                      }
                      value={createForm.sku}
                      onChange={e => {
                        setCreateForm(f => ({ ...f, sku: e.target.value.toUpperCase() }));
                        setSkuAutoGenerated(false);
                      }}
                      className={`w-full px-3 py-2 pr-8 border-[0.5px] rounded-lg text-sm focus:outline-none font-mono transition-colors ${
                        skuAutoGenerated
                          ? 'border-brand-teal bg-[var(--color-status-success-tint)] focus:border-brand-teal'
                          : 'border-[var(--color-border-secondary)] focus:border-brand-teal'
                      }`}
                    />
                    {/* Spinner while generating */}
                    {skuGenerating && (
                      <div className="absolute right-2.5 top-1/2 -translate-y-1/2">
                        <svg className="animate-spin w-3.5 h-3.5 text-brand-teal" fill="none" viewBox="0 0 24 24">
                          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z"/>
                        </svg>
                      </div>
                    )}
                    {/* Regenerate button when auto-generated */}
                    {skuAutoGenerated && !skuGenerating && createForm.category && createForm.brand && (
                      <button
                        type="button"
                        title="Regenerate SKU"
                        onClick={() => generateSku(createForm.category, createForm.brand)}
                        className="absolute right-2 top-1/2 -translate-y-1/2 text-brand-teal hover:text-[var(--color-brand-teal-hover)] transition-colors"
                      >
                        <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                          <path d="M23 4v6h-6"/><path d="M1 20v-6h6"/>
                          <path d="M3.51 9a9 9 0 0114.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0020.49 15"/>
                        </svg>
                      </button>
                    )}
                  </div>
                  {!createForm.category && !createForm.brand && modalMode === 'create' && (
                    <p className="text-xs text-[var(--color-text-secondary)] mt-1">SKU auto-fills after selecting category &amp; brand</p>
                  )}
                </div>
                <div>
                  <label className="block text-sm text-[var(--color-text-secondary)] mb-1">Brand <span className="text-[var(--color-status-danger)]">*</span></label>
                  <div className="relative brand-dropdown-container">
                    <input
                      type="text"
                      placeholder="Search manufacturer..."
                      value={brandSearch}
                      onChange={e => {
                        const val = e.target.value;
                        setBrandSearch(val);
                        setShowBrandDropdown(true);
                        // Clear brand ID when user edits the text
                        setCreateForm(f => ({ ...f, brand: '' }));
                      }}
                      onFocus={() => setShowBrandDropdown(true)}
                      className={`w-full px-3 py-2 border-[0.5px] rounded-lg text-sm focus:outline-none focus:border-brand-teal ${
                        createForm.brand ? 'border-brand-teal bg-[var(--color-status-success-tint)]' : 'border-[var(--color-border-secondary)]'
                      }`}
                    />
                    {/* Matched indicator */}
                    {createForm.brand && (
                      <div className="absolute right-2 top-1/2 -translate-y-1/2 text-brand-teal">
                        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3">
                          <polyline points="20 6 9 17 4 12"/>
                        </svg>
                      </div>
                    )}
                    {showBrandDropdown && brandSearch && (
                      <div className="absolute z-10 w-full mt-1 bg-white border-[0.5px] border-[var(--color-border-secondary)] rounded-lg shadow-lg max-h-48 overflow-y-auto">
                        {(manufacturers || [])
                          .filter(m => m.name.toLowerCase().includes(brandSearch.toLowerCase()))
                          .map(manufacturer => (
                            <div
                              key={manufacturer._id}
                              onMouseDown={e => e.preventDefault()}
                              onClick={() => {
                                setCreateForm(f => ({ ...f, brand: manufacturer._id }));
                                setBrandSearch(manufacturer.name);
                                setShowBrandDropdown(false);
                              }}
                              className={`px-3 py-2 hover:bg-[var(--color-background-tertiary)] cursor-pointer text-sm flex items-center justify-between ${
                                createForm.brand === manufacturer._id ? 'bg-[var(--color-status-success-tint)] text-brand-teal font-semibold' : ''
                              }`}
                            >
                              <span>{manufacturer.name}</span>
                              {manufacturer.country && (
                                <span className="text-xs text-[var(--color-text-secondary)] ml-2">
                                  ({manufacturer.country})
                                </span>
                              )}
                            </div>
                          ))}
                        {/* "+ Add as new brand" option when no exact match exists */}
                        {brandSearch.trim() && !(manufacturers || []).some(m => m.name.toLowerCase() === brandSearch.trim().toLowerCase()) && (
                          <div
                            onMouseDown={e => e.preventDefault()}
                            onClick={async () => {
                              const name = brandSearch.trim();
                              try {
                                const token = localStorage.getItem('Mediport_token');
                                const res = await fetch(`${API}/manufacturers`, {
                                  method: 'POST',
                                  headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
                                  body: JSON.stringify({ name }),
                                });
                                const data = await res.json();
                                if (data.success && data.manufacturer) {
                                  // Add to local state so it appears immediately
                                  setManufacturers(prev => [...prev, data.manufacturer].sort((a, b) => a.name.localeCompare(b.name)));
                                  setCreateForm(f => ({ ...f, brand: data.manufacturer._id }));
                                  setBrandSearch(data.manufacturer.name);
                                  setShowBrandDropdown(false);
                                  showMessage(`Brand "${data.manufacturer.name}" created`, 'success');
                                } else {
                                  showMessage(data.message || 'Failed to create brand', 'error');
                                }
                              } catch (_e) {
                                showMessage('Failed to create brand', 'error');
                              }
                            }}
                            className="px-3 py-2 hover:bg-[var(--color-status-success-tint)] cursor-pointer text-sm flex items-center gap-2 text-brand-teal font-medium border-t border-[var(--color-border-tertiary)]"
                          >
                            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                              <path d="M12 5v14M5 12h14"/>
                            </svg>
                            Add &ldquo;{brandSearch.trim()}&rdquo; as new brand
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                  {/* Only show hint when dropdown is open and user hasn't selected yet */}
                  {brandSearch && !createForm.brand && showBrandDropdown && (
                    <p className="text-xs text-[var(--color-status-warning)] mt-1">Select a manufacturer from the list</p>
                  )}
                </div>
              </div>

              <div>
                <label className="block text-sm text-[var(--color-text-secondary)] mb-1">Product Name <span className="text-[var(--color-status-danger)]">*</span></label>
                <input
                  type="text"
                  placeholder="e.g. Siemens ADVIA 2120i Hematology Analyzer"
                  value={createForm.name}
                  onChange={e => setCreateForm(f => ({ ...f, name: e.target.value }))}
                  className="w-full px-3 py-2 border-[0.5px] border-[var(--color-border-secondary)] rounded-lg text-sm focus:outline-none focus:border-brand-teal"
                />
              </div>

              <div>
                <label className="block text-sm text-[var(--color-text-secondary)] mb-1">Description <span className="text-[var(--color-status-danger)]">*</span></label>
                <textarea
                  rows={3}
                  placeholder="Detailed product description…"
                  value={createForm.description}
                  onChange={e => setCreateForm(f => ({ ...f, description: e.target.value }))}
                  className="w-full px-3 py-2 border-[0.5px] border-[var(--color-border-secondary)] rounded-lg text-sm focus:outline-none focus:border-brand-teal resize-none"
                />
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm text-[var(--color-text-secondary)] mb-1">Category <span className="text-[var(--color-status-danger)]">*</span></label>
                  <select
                    value={createForm.category}
                    onChange={e => {
                      const newCat = e.target.value;
                      setCreateForm(f => ({ ...f, category: newCat, subcategory: '' }));
                    }}
                    className="w-full px-3 py-2 border-[0.5px] border-[var(--color-border-secondary)] rounded-lg text-sm bg-white focus:outline-none focus:border-brand-teal"
                  >
                    <option value="">Select category...</option>
                    {(categories || []).map(c => (
                      <option key={c._id} value={c._id}>
                        {c.name}
                      </option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block text-sm text-[var(--color-text-secondary)] mb-1">Subcategory</label>
                  <input
                    type="text"
                    placeholder="e.g. Hematology"
                    value={createForm.subcategory}
                    onChange={e => setCreateForm(f => ({ ...f, subcategory: e.target.value }))}
                    className="w-full px-3 py-2 border-[0.5px] border-[var(--color-border-secondary)] rounded-lg text-sm focus:outline-none focus:border-brand-teal"
                  />
                </div>
              </div>

              {/* Pricing */}
              <div className="grid grid-cols-3 gap-4">
                <div>
                  <label className="block text-sm text-[var(--color-text-secondary)] mb-1">Price (৳) <span className="text-[var(--color-status-danger)]">*</span></label>
                  <input
                    type="number"
                    min="0"
                    placeholder="0"
                    value={createForm.price}
                    onChange={e => setCreateForm(f => ({ ...f, price: e.target.value }))}
                    className="w-full px-3 py-2 border-[0.5px] border-[var(--color-border-secondary)] rounded-lg text-sm focus:outline-none focus:border-brand-teal"
                  />
                </div>
                <div>
                  <label className="block text-sm text-[var(--color-text-secondary)] mb-1">B2B Price (৳)</label>
                  <input
                    type="number"
                    min="0"
                    placeholder="0"
                    value={createForm.b2bPrice}
                    onChange={e => setCreateForm(f => ({ ...f, b2bPrice: e.target.value }))}
                    className="w-full px-3 py-2 border-[0.5px] border-[var(--color-border-secondary)] rounded-lg text-sm focus:outline-none focus:border-brand-teal"
                  />
                  {!createForm.b2bPrice && createForm.price && (
                    <div className="text-xs text-[var(--color-text-tertiary)] mt-1">
                      Auto: ৳{Math.round(Number(createForm.price) * 0.78).toLocaleString()} (78% of retail)
                    </div>
                  )}
                </div>
                <div>
                  <label className="block text-sm text-[var(--color-text-secondary)] mb-1">Old Price (৳)</label>
                  <input
                    type="number"
                    min="0"
                    placeholder="0"
                    value={createForm.oldPrice}
                    onChange={e => setCreateForm(f => ({ ...f, oldPrice: e.target.value }))}
                    className="w-full px-3 py-2 border-[0.5px] border-[var(--color-border-secondary)] rounded-lg text-sm focus:outline-none focus:border-brand-teal"
                  />
                </div>
              </div>

              {/* Stock & Unit */}
              <div className="grid grid-cols-3 gap-4">
                <div>
                  <label className="block text-sm text-[var(--color-text-secondary)] mb-1">Stock <span className="text-[var(--color-status-danger)]">*</span></label>
                  <input
                    type="number"
                    min="0"
                    placeholder="0"
                    value={createForm.stock}
                    onChange={e => setCreateForm(f => ({ ...f, stock: e.target.value }))}
                    className="w-full px-3 py-2 border-[0.5px] border-[var(--color-border-secondary)] rounded-lg text-sm focus:outline-none focus:border-brand-teal"
                  />
                </div>
                <div>
                  <label className="block text-sm text-[var(--color-text-secondary)] mb-1">Low Stock Alert</label>
                  <input
                    type="number"
                    min="0"
                    placeholder="10"
                    value={createForm.lowStockThreshold}
                    onChange={e => setCreateForm(f => ({ ...f, lowStockThreshold: e.target.value }))}
                    className="w-full px-3 py-2 border-[0.5px] border-[var(--color-border-secondary)] rounded-lg text-sm focus:outline-none focus:border-brand-teal"
                  />
                </div>
                <div>
                  <label className="block text-sm text-[var(--color-text-secondary)] mb-1">Unit</label>
                  <select
                    value={createForm.unit}
                    onChange={e => setCreateForm(f => ({ ...f, unit: e.target.value }))}
                    className="w-full px-3 py-2 border-[0.5px] border-[var(--color-border-secondary)] rounded-lg text-sm bg-white focus:outline-none focus:border-brand-teal"
                  >
                    {UNITS.map(u => <option key={u} value={u}>{u}</option>)}
                  </select>
                </div>
              </div>

              {/* Certifications */}
              <div>
                <label className="block text-sm text-[var(--color-text-secondary)] mb-2">Certifications</label>
                <div className="flex gap-3 flex-wrap">
                  {CERTIFICATIONS.map(cert => (
                    <label key={cert} className="flex items-center gap-1.5 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={createForm.certifications.includes(cert)}
                        onChange={e => {
                          setCreateForm(f => ({
                            ...f,
                            certifications: e.target.checked
                              ? [...f.certifications, cert]
                              : f.certifications.filter(c => c !== cert)
                          }));
                        }}
                        className="accent-brand-teal"
                      />
                      <span className="text-xs">{cert}</span>
                    </label>
                  ))}
                </div>
              </div>

              {/* Storage Temperature + Hazard Class */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm text-[var(--color-text-secondary)] mb-2">Storage Temperature</label>
                  <div className="space-y-2">
                    {[
                      { val: 'room', label: '🌡️ Room temp (15–25°C)' },
                      { val: 'cold', label: '❄️ Cold (2–8°C)' },
                      { val: 'frozen', label: '🧊 Frozen (−20°C)' },
                    ].map(opt => (
                      <label key={opt.val} className="flex items-center gap-2 cursor-pointer">
                        <input
                          type="radio"
                          name="storageTemp"
                          value={opt.val}
                          checked={createForm.storageTemp === opt.val}
                          onChange={() => setCreateForm(f => ({ ...f, storageTemp: opt.val }))}
                          className="accent-brand-teal"
                        />
                        <span className="text-xs">{opt.label}</span>
                      </label>
                    ))}
                  </div>
                </div>
                <div>
                  <label className="block text-sm text-[var(--color-text-secondary)] mb-2">Hazard Class</label>
                  <div className="space-y-2">
                    {[
                      { val: 'safe', label: '✅ Safe' },
                      { val: 'biohazard', label: '⚠️ Biohazard' },
                      { val: 'chemical', label: '⚠️ Chemical' },
                    ].map(opt => (
                      <label key={opt.val} className="flex items-center gap-2 cursor-pointer">
                        <input
                          type="radio"
                          name="hazardClass"
                          value={opt.val}
                          checked={createForm.hazardClass === opt.val}
                          onChange={() => setCreateForm(f => ({ ...f, hazardClass: opt.val }))}
                          className="accent-brand-teal"
                        />
                        <span className="text-xs">{opt.label}</span>
                      </label>
                    ))}
                  </div>
                </div>
              </div>

              {/* Specifications */}
              <div>
                <label className="block text-sm text-[var(--color-text-secondary)] mb-2">
                  Specifications <span className="text-xs font-normal">(technical details)</span>
                </label>
                {createForm.specifications.map((spec, idx) => (
                  <div key={idx} className="grid grid-cols-[1fr_1fr_32px] gap-2 mb-2">
                    <input
                      placeholder="Key (e.g. Leads)"
                      value={spec.key}
                      onChange={e => {
                        const updated = [...createForm.specifications];
                        updated[idx].key = e.target.value;
                        setCreateForm(f => ({ ...f, specifications: updated }));
                      }}
                      className="px-3 py-2 border-[0.5px] border-[var(--color-border-secondary)] rounded-lg text-xs focus:outline-none focus:border-brand-teal"
                    />
                    <input
                      placeholder="Value (e.g. 12)"
                      value={spec.value}
                      onChange={e => {
                        const updated = [...createForm.specifications];
                        updated[idx].value = e.target.value;
                        setCreateForm(f => ({ ...f, specifications: updated }));
                      }}
                      className="px-3 py-2 border-[0.5px] border-[var(--color-border-secondary)] rounded-lg text-xs focus:outline-none focus:border-brand-teal"
                    />
                    <button
                      type="button"
                      onClick={() => setCreateForm(f => ({
                        ...f,
                        specifications: f.specifications.filter((_, i) => i !== idx)
                      }))}
                      className="bg-[var(--color-status-danger-tint)] border-[0.5px] border-[var(--color-status-danger)] rounded-lg text-[var(--color-status-danger)] text-lg hover:bg-[var(--color-status-danger-tint)] transition-colors"
                    >
                      ×
                    </button>
                  </div>
                ))}
                <button
                  type="button"
                  onClick={() => setCreateForm(f => ({
                    ...f,
                    specifications: [...f.specifications, { key: '', value: '' }]
                  }))}
                  className="text-xs px-3 py-2 rounded-lg border-[0.5px] border-[var(--color-border-secondary)] bg-transparent hover:bg-[var(--color-background-tertiary)] transition-colors"
                >
                  + Add specification
                </button>
              </div>

              {/* Size Variants */}
              <div>
                <label className="block text-sm text-[var(--color-text-secondary)] mb-2 flex items-center gap-2">
                  📏 Size Variants
                  <span className="text-xs font-normal">(for clothing, PPE, etc.)</span>
                </label>
                <div className="space-y-2">
                  {(createForm.sizes || []).map((size, idx) => (
                    <div key={idx} className="flex items-center gap-2 bg-[var(--color-background-secondary)] p-3 rounded-lg">
                      <select
                        value={size.name}
                        onChange={e => {
                          const newSizes = [...(createForm.sizes || [])];
                          newSizes[idx] = { ...newSizes[idx], name: e.target.value };
                          setCreateForm(f => ({ ...f, sizes: newSizes }));
                        }}
                        className="px-3 py-2 border-[0.5px] border-[var(--color-border-secondary)] rounded-lg text-xs focus:outline-none focus:border-brand-teal w-24"
                      >
                        <option value="">Size</option>
                        <option value="XS">XS</option>
                        <option value="S">S</option>
                        <option value="M">M</option>
                        <option value="L">L</option>
                        <option value="XL">XL</option>
                        <option value="XXL">XXL</option>
                        <option value="XXXL">XXXL</option>
                      </select>
                      <input
                        type="number"
                        value={size.stock || ''}
                        onChange={e => {
                          const newSizes = [...(createForm.sizes || [])];
                          newSizes[idx] = { ...newSizes[idx], stock: parseInt(e.target.value) || 0 };
                          setCreateForm(f => ({ ...f, sizes: newSizes }));
                        }}
                        placeholder="Stock"
                        className="px-3 py-2 border-[0.5px] border-[var(--color-border-secondary)] rounded-lg text-xs focus:outline-none focus:border-brand-teal w-24"
                      />
                      <input
                        type="number"
                        value={size.priceAdjustment || ''}
                        onChange={e => {
                          const newSizes = [...(createForm.sizes || [])];
                          newSizes[idx] = { ...newSizes[idx], priceAdjustment: parseInt(e.target.value) || 0 };
                          setCreateForm(f => ({ ...f, sizes: newSizes }));
                        }}
                        placeholder="Price adj. (৳)"
                        className="px-3 py-2 border-[0.5px] border-[var(--color-border-secondary)] rounded-lg text-xs focus:outline-none focus:border-brand-teal flex-1"
                      />
                      <label className="flex items-center gap-1 text-sm whitespace-nowrap">
                        <input
                          type="checkbox"
                          checked={size.isAvailable !== false}
                          onChange={e => {
                            const newSizes = [...(createForm.sizes || [])];
                            newSizes[idx] = { ...newSizes[idx], isAvailable: e.target.checked };
                            setCreateForm(f => ({ ...f, sizes: newSizes }));
                          }}
                          className="accent-brand-teal"
                        />
                        Available
                      </label>
                      <button
                        type="button"
                        onClick={() => setCreateForm(f => ({
                          ...f,
                          sizes: (f.sizes || []).filter((_, i) => i !== idx)
                        }))}
                        className="w-8 h-8 bg-[var(--color-status-danger-tint)] border-[0.5px] border-[var(--color-status-danger)] rounded-lg text-[var(--color-status-danger)] text-lg hover:bg-[var(--color-status-danger-tint)] transition-colors flex items-center justify-center flex-shrink-0"
                      >
                        ×
                      </button>
                    </div>
                  ))}
                  <div className="flex gap-2">
                    <button
                      type="button"
                      onClick={() => setCreateForm(f => ({
                        ...f,
                        sizes: [...(f.sizes || []), { name: 'M', stock: 0, priceAdjustment: 0, isAvailable: true }]
                      }))}
                      className="text-xs px-3 py-2 rounded-lg border-[0.5px] border-[var(--color-border-secondary)] bg-transparent hover:bg-[var(--color-background-tertiary)] transition-colors"
                    >
                      + Add size variant
                    </button>
                    <button
                      type="button"
                      onClick={() => {
                        const allSizes = ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'];
                        const existingSizes = (createForm.sizes || []).map(s => s.name);
                        const newSizes = allSizes
                          .filter(sizeName => !existingSizes.includes(sizeName))
                          .map(sizeName => ({
                            name: sizeName,
                            stock: 10,
                            priceAdjustment: 0,
                            isAvailable: true
                          }));
                        
                        if (newSizes.length > 0) {
                          setCreateForm(f => ({
                            ...f,
                            sizes: [...(f.sizes || []), ...newSizes]
                          }));
                          showMessage(`Added ${newSizes.length} size variant(s)`, 'success');
                        } else {
                          showMessage('All sizes already added', 'error');
                        }
                      }}
                      className="text-xs px-3 py-2 rounded-lg border-[0.5px] border-brand-teal bg-brand-teal/5 text-brand-teal hover:bg-brand-teal/10 transition-colors font-medium"
                    >
                      ✨ Add All Sizes
                    </button>
                  </div>
                  <div className="text-xs text-[var(--color-text-tertiary)] mt-1">
                    💡 For products like clothing, PPE, support belts. Price adj. = extra cost for larger sizes (e.g., +50 for XL)
                  </div>
                </div>
              </div>

              {/* Tags */}
              <div>
                <label className="block text-sm text-[var(--color-text-secondary)] mb-2">
                  Tags <span className="text-xs font-normal">(for search)</span>
                </label>
                <div className="border-[0.5px] border-[var(--color-border-secondary)] rounded-lg p-2 min-h-[44px] flex flex-wrap gap-2 items-center">
                  {createForm.tags.map((tag, i) => (
                    <span key={i} className="bg-[var(--color-status-warning-tint)] text-[var(--color-status-warning)] rounded px-2 py-1 text-xs flex items-center gap-1">
                      {tag}
                      <button
                        type="button"
                        onClick={() => setCreateForm(f => ({
                          ...f,
                          tags: f.tags.filter((_, idx) => idx !== i)
                        }))}
                        className="text-sm hover:text-[var(--color-status-danger)]"
                      >
                        ×
                      </button>
                    </span>
                  ))}
                  <input
                    value={createForm.tagInput || ''}
                    onChange={e => setCreateForm(f => ({ ...f, tagInput: e.target.value }))}
                    onKeyDown={e => {
                      if ((e.key === 'Enter' || e.key === ',') && createForm.tagInput?.trim()) {
                        e.preventDefault();
                        const val = createForm.tagInput.trim();
                        if (!createForm.tags.includes(val)) {
                          setCreateForm(f => ({ ...f, tags: [...f.tags, val], tagInput: '' }));
                        }
                      }
                    }}
                    placeholder={createForm.tags.length ? '' : 'Type and press Enter...'}
                    className="border-none outline-none text-xs flex-1 min-w-[120px] bg-transparent"
                  />
                </div>
                <div className="text-xs text-[var(--color-text-tertiary)] mt-1">
                  e.g. ecg, cardiac, diagnostic — press Enter after each
                </div>
              </div>

              {/* Compatible With */}
              <div>
                <label className="block text-sm text-[var(--color-text-secondary)] mb-2">
                  Compatible With <span className="text-xs font-normal">(related products)</span>
                </label>
                <div className="border-[0.5px] border-[var(--color-border-secondary)] rounded-lg p-2 min-h-[44px] flex flex-wrap gap-2 items-center">
                  {createForm.compatibleWith.map((item, i) => (
                    <span key={i} className="bg-[var(--color-status-info-tint)] text-[var(--color-status-info)] rounded px-2 py-1 text-xs flex items-center gap-1">
                      {item}
                      <button
                        type="button"
                        onClick={() => setCreateForm(f => ({
                          ...f,
                          compatibleWith: f.compatibleWith.filter((_, idx) => idx !== i)
                        }))}
                        className="text-sm hover:text-[var(--color-status-danger)]"
                      >
                        ×
                      </button>
                    </span>
                  ))}
                  <input
                    value={createForm.compatibleInput || ''}
                    onChange={e => setCreateForm(f => ({ ...f, compatibleInput: e.target.value }))}
                    onKeyDown={e => {
                      if ((e.key === 'Enter' || e.key === ',') && createForm.compatibleInput?.trim()) {
                        e.preventDefault();
                        const val = createForm.compatibleInput.trim();
                        if (!createForm.compatibleWith.includes(val)) {
                          setCreateForm(f => ({ ...f, compatibleWith: [...f.compatibleWith, val], compatibleInput: '' }));
                        }
                      }
                    }}
                    placeholder={createForm.compatibleWith.length ? '' : 'Type product names...'}
                    className="border-none outline-none text-xs flex-1 min-w-[120px] bg-transparent"
                  />
                </div>
              </div>

              {/* Reagent-specific fields */}
              {(() => {
                const selectedCategory = categories?.find(c => c._id === createForm.category);
                return selectedCategory?.name === 'Laboratory Reagents' && (
                  <div className="bg-[var(--color-status-info-tint)] rounded-lg p-4">
                    <div className="text-xs font-semibold text-[var(--color-status-info)] mb-3 flex items-center gap-2">
                      🧪 Reagent Details
                    </div>
                    <div className="grid grid-cols-2 gap-3">
                      <div>
                        <label className="block text-sm text-[var(--color-text-secondary)] mb-1">
                          Lot Number
                        </label>
                        <input
                          value={createForm.lotNumber}
                          onChange={e => setCreateForm(f => ({ ...f, lotNumber: e.target.value }))}
                          placeholder="e.g. LOT-2025-08841"
                          className="w-full px-3 py-2 border-[0.5px] border-[var(--color-border-secondary)] rounded-lg text-xs focus:outline-none focus:border-brand-teal"
                        />
                      </div>
                      <div>
                        <label className="block text-sm text-[var(--color-text-secondary)] mb-1">Expiry Date</label>
                        <input
                          type="date"
                          value={createForm.expiryDate}
                          onChange={e => setCreateForm(f => ({ ...f, expiryDate: e.target.value }))}
                          min={new Date().toISOString().split('T')[0]}
                          className="w-full px-3 py-2 border-[0.5px] border-[var(--color-border-secondary)] rounded-lg text-xs focus:outline-none focus:border-brand-teal"
                        />
                      </div>
                    </div>
                  </div>
                );
              })()}

              {/* Toggles */}
              <div className="flex gap-6">
                <label className="flex items-center gap-2 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={createForm.isFeatured}
                    onChange={e => setCreateForm(f => ({ ...f, isFeatured: e.target.checked }))}
                    className="accent-brand-teal"
                  />
                  <span className="text-xs">Featured product</span>
                </label>
                <label className="flex items-center gap-2 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={createForm.isActive}
                    onChange={e => setCreateForm(f => ({ ...f, isActive: e.target.checked }))}
                    className="accent-brand-teal"
                  />
                  <span className="text-xs">Active (visible on site)</span>
                </label>
              </div>
            </div>

            {/* Footer */}
            <div className="flex gap-3 px-4 sm:px-6 py-4 border-t-[0.5px] border-[var(--color-border-tertiary)] sticky bottom-0 bg-white">
              <button
                onClick={handleCreateProduct}
                disabled={creating}
                className="flex-1 min-h-[48px] py-2.5 bg-brand-navy text-white rounded-lg text-sm font-semibold disabled:opacity-50 hover:bg-[var(--color-brand-navy-hover)] transition-colors"
              >
                {creating ? 'Saving…' : modalMode === 'edit' ? 'Save Changes' : 'Create Product'}
              </button>
              <button
                onClick={closeModal}
                className="flex-1 min-h-[48px] py-2.5 border-[0.5px] border-[var(--color-border-secondary)] rounded-lg text-sm hover:bg-[var(--color-background-tertiary)] transition-colors"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Filters */}
      <div className="p-4 border-b-[0.5px] border-[var(--color-border-tertiary)] bg-[var(--color-background-secondary)]">
        {/* Search Bar */}
        <div className="mb-3">
          <div className="relative">
            <input
              type="text"
              placeholder="Search by product name, SKU, or description..."
              value={searchQuery}
              onChange={e => { setSearchQuery(e.target.value); setPage(1); }}
              className="w-full px-4 py-2.5 pl-10 min-h-[48px] text-base sm:text-sm border-[0.5px] border-[var(--color-border-secondary)] rounded-lg font-[family-name:var(--font-plus-jakarta)] bg-white focus:outline-none focus:border-brand-teal focus:ring-2 focus:ring-brand-teal/10 transition-all"
            />
            <svg className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[var(--color-text-secondary)]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
            {searchQuery && (
              <button
                onClick={() => { setSearchQuery(''); setPage(1); }}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-[var(--color-text-secondary)] hover:text-danger transition-colors"
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            )}
          </div>
        </div>

        {/* Filter Pills - Stacked on mobile, horizontal on desktop */}
        <div className="space-y-2">
          {/* Row 1: Category (full width on mobile) */}
          <div className="relative">
            <select
              value={categoryFilter}
              onChange={e => { setCategoryFilter(e.target.value); setPage(1); }}
              className={`w-full pl-3 pr-8 min-h-[44px] py-2 border-[0.5px] rounded-lg text-sm font-[family-name:var(--font-plus-jakarta)] bg-white focus:outline-none transition-all appearance-none cursor-pointer ${
                categoryFilter 
                  ? 'border-brand-teal bg-[var(--color-status-success-tint)] text-brand-teal font-semibold shadow-sm' 
                  : 'border-[var(--color-border-secondary)] hover:border-brand-teal text-[var(--color-text-primary)]'
              }`}
            >
              <option value="">📂 All categories</option>
              {(categories || []).map(c => (
                <option key={c._id} value={c._id}>
                  {c.name}
                </option>
              ))}
            </select>
            <svg className={`absolute right-2 top-1/2 -translate-y-1/2 w-4 h-4 pointer-events-none ${categoryFilter ? 'text-brand-teal' : 'text-[var(--color-text-secondary)]'}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
            </svg>
          </div>

          {/* Row 2: Brand & Status (2 columns on mobile) */}
          <div className="grid grid-cols-2 gap-2">
            <div className="relative">
              <select
                value={brandFilter}
                onChange={e => { setBrandFilter(e.target.value); setPage(1); }}
                className={`w-full pl-3 pr-8 min-h-[44px] py-2 border-[0.5px] rounded-lg text-sm font-[family-name:var(--font-plus-jakarta)] bg-white focus:outline-none transition-all appearance-none cursor-pointer ${
                  brandFilter 
                    ? 'border-brand-teal bg-[var(--color-status-success-tint)] text-brand-teal font-semibold shadow-sm' 
                    : 'border-[var(--color-border-secondary)] hover:border-brand-teal text-[var(--color-text-primary)]'
                }`}
              >
                <option value="">🏭 All brands</option>
                {(manufacturers || []).map(m => (
                  <option key={m._id} value={m._id}>
                    {m.name}
                  </option>
                ))}
              </select>
              <svg className={`absolute right-2 top-1/2 -translate-y-1/2 w-4 h-4 pointer-events-none ${brandFilter ? 'text-brand-teal' : 'text-[var(--color-text-secondary)]'}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
              </svg>
            </div>

            <div className="relative">
              <select
                value={statusFilter}
                onChange={e => { setStatusFilter(e.target.value); setPage(1); }}
                className={`w-full pl-3 pr-8 min-h-[44px] py-2 border-[0.5px] rounded-lg text-sm font-[family-name:var(--font-plus-jakarta)] bg-white focus:outline-none transition-all appearance-none cursor-pointer ${
                  statusFilter 
                    ? 'border-brand-teal bg-[var(--color-status-success-tint)] text-brand-teal font-semibold shadow-sm' 
                    : 'border-[var(--color-border-secondary)] hover:border-brand-teal text-[var(--color-text-primary)]'
                }`}
              >
                <option value="">⚡ All status</option>
                <option value="active">✓ Active</option>
                <option value="inactive">✗ Inactive</option>
                <option value="featured">⭐ Featured</option>
              </select>
              <svg className={`absolute right-2 top-1/2 -translate-y-1/2 w-4 h-4 pointer-events-none ${statusFilter ? 'text-brand-teal' : 'text-[var(--color-text-secondary)]'}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
              </svg>
            </div>
          </div>

          {/* Row 3: Stock Level (full width on mobile) */}
          <div className="relative">
            <select
              value={stockFilter}
              onChange={e => { setStockFilter(e.target.value); setPage(1); }}
              className={`w-full pl-3 pr-8 min-h-[44px] py-2 border-[0.5px] rounded-lg text-sm font-[family-name:var(--font-plus-jakarta)] bg-white focus:outline-none transition-all appearance-none cursor-pointer ${
                stockFilter 
                  ? 'border-brand-teal bg-[var(--color-status-success-tint)] text-brand-teal font-semibold shadow-sm' 
                  : 'border-[var(--color-border-secondary)] hover:border-brand-teal text-[var(--color-text-primary)]'
              }`}
            >
              <option value="">📦 All stock levels</option>
              <option value="instock">✓ In Stock</option>
              <option value="lowstock">⚠️ Low Stock</option>
              <option value="outofstock">✗ Out of Stock</option>
            </select>
            <svg className={`absolute right-2 top-1/2 -translate-y-1/2 w-4 h-4 pointer-events-none ${stockFilter ? 'text-brand-teal' : 'text-[var(--color-text-secondary)]'}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
            </svg>
          </div>

          {/* Row 4: Clear button & Results count */}
          <div className="flex gap-2">
            {/* Clear Filters Button */}
            {(categoryFilter || brandFilter || statusFilter || stockFilter || searchQuery) && (
              <button
                onClick={() => {
                  setCategoryFilter('');
                  setBrandFilter('');
                  setStatusFilter('');
                  setStockFilter('');
                  setSearchQuery('');
                  setPage(1);
                }}
                className="flex-1 min-h-[44px] px-3 py-2 border-[0.5px] border-danger bg-[var(--color-status-danger-tint)] text-danger rounded-lg text-xs font-medium hover:bg-danger hover:text-white transition-all flex items-center justify-center gap-1.5 shadow-sm"
              >
                <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
                <span className="hidden sm:inline">Clear all</span>
                <span className="sm:hidden">Clear</span>
              </button>
            )}

            {/* Results Count */}
            <div className={`flex items-center justify-center gap-2 px-3 py-2 min-h-[44px] bg-white border-[0.5px] border-[var(--color-border-secondary)] rounded-lg ${
              (categoryFilter || brandFilter || statusFilter || stockFilter || searchQuery) ? 'flex-1' : 'w-full'
            }`}>
              <svg className="w-4 h-4 text-[var(--color-text-secondary)]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" />
              </svg>
              <span className="text-sm font-semibold text-[var(--color-text-primary)]">
                {total}
              </span>
              <span className="text-sm text-[var(--color-text-secondary)]">
                product{total !== 1 ? 's' : ''}
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* ── Mobile Card View (< md) ─────────────────────────────────────── */}
      <div className="md:hidden">
        {loading ? (
          <div className="p-8 text-center text-xs text-[var(--color-text-secondary)]">Loading products…</div>
        ) : products.length === 0 ? (
          <EmptyState
          icon="🔍"
          title="No products found"
          description="No products match the current search or filters. Try clearing them or adding a new product."
        />
        ) : (
          <div className="divide-y divide-[var(--color-border-tertiary)]">
            {products.map(product => {
              const stockStatus = getStockStatus(product);
              const categoryName = typeof product.category === 'object' ? product.category?.name : product.category;
              const brandName = typeof product.brand === 'object' ? product.brand?.name : product.brand;
              
              // Handle different image structures more robustly
              let img = null;
              if (product.images && product.images.length > 0) {
                const imgRaw = product.images[0];
                // Handle both string URLs and object {url: '...'} formats
                img = typeof imgRaw === 'string' ? imgRaw : imgRaw?.url;
              } else if (product.image) {
                // Fallback to single 'image' field if it exists
                img = typeof product.image === 'string' ? product.image : product.image?.url;
              }
              
              return (
                <div key={product._id} className="p-4 flex gap-3">
                  {/* Product image */}
                  <div className="w-14 h-14 rounded-lg overflow-hidden bg-[var(--color-background-secondary)] flex-shrink-0 border-[0.5px] border-[var(--color-border-tertiary)]">
                    {img ? (
                      // eslint-disable-next-line @next/next/no-img-element
                      <img 
                        src={img} 
                        alt={product.name} 
                        className="w-full h-full object-cover"
                        crossOrigin="anonymous"
                        referrerPolicy="no-referrer"
                        loading="lazy"
                      />
                    ) : (
                      <div className="w-full h-full flex items-center justify-center text-2xl">🏥</div>
                    )}
                  </div>

                  {/* Product info */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-start justify-between gap-2 mb-1">
                      <p className="text-sm font-semibold text-[var(--color-text-primary)] leading-tight line-clamp-2">{product.name}</p>
                      <span className={`text-xs px-2 py-[3px] rounded font-medium flex-shrink-0 ${stockStatus.color}`}>
                        {stockStatus.label}
                      </span>
                    </div>
                    <p className="text-xs font-mono text-[var(--color-text-secondary)] mb-1">{product.sku}</p>
                    <div className="flex flex-wrap items-center gap-x-3 gap-y-1 mb-2">
                      {brandName && <span className="text-xs text-brand-teal font-medium">{brandName}</span>}
                      {categoryName && <span className="text-xs text-[var(--color-text-secondary)]">{categoryName}</span>}
                      <span className="text-xs text-[var(--color-text-secondary)]">Stock: <span className="font-semibold text-[var(--color-text-primary)]">{product.stock}</span></span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-sm font-semibold text-brand-navy">৳{(product.price || 0).toLocaleString()}</span>
                      <div className="flex gap-2">
                        <button
                          onClick={() => handleEditOpen(product)}
                          className="min-h-[36px] px-3 text-xs text-brand-teal font-semibold border border-brand-teal rounded-lg hover:bg-[var(--color-status-success-tint)] transition-colors"
                        >
                          Edit
                        </button>
                        <button
                          onClick={() => handleDelete(product._id)}
                          className="min-h-[36px] px-3 text-xs text-danger font-semibold border border-danger rounded-lg hover:bg-[var(--color-status-danger-tint)] transition-colors"
                        >
                          Delete
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* ── Desktop Table View (≥ md) ────────────────────────────────────── */}
      <div className="hidden md:block overflow-x-auto">
        {loading ? (
          <div className="p-8 text-center text-xs text-[var(--color-text-secondary)]">Loading products…</div>
        ) : products.length === 0 ? (
          <EmptyState
          icon="🔍"
          title="No products found"
          description="No products match the current search or filters. Try clearing them or adding a new product."
        />
        ) : (
          <table className="w-full">
            <thead>
              <tr className="border-b-[0.5px] border-[var(--color-border-tertiary)]">
                {['Image', 'SKU', 'Product Name', 'Category', 'Stock', 'Price', 'Status', 'Actions'].map(h => (
                  <th key={h} className="text-left px-4 py-3 text-xs font-semibold text-[var(--color-text-secondary)] font-[family-name:var(--font-plus-jakarta)]">
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {products.map(product => {
                const stockStatus = getStockStatus(product);
                const categoryName = typeof product.category === 'object' ? product.category?.name : product.category;
                const brandName = typeof product.brand === 'object' ? product.brand?.name : product.brand;
                
                // Handle different image structures
                let img = null;
                if (product.images && product.images.length > 0) {
                  const imgRaw = product.images[0];
                  img = typeof imgRaw === 'string' ? imgRaw : imgRaw?.url;
                } else if (product.image) {
                  img = typeof product.image === 'string' ? product.image : product.image?.url;
                }
                
                return (
                  <tr key={product._id} className="border-b-[0.5px] border-[var(--color-border-tertiary)] hover:bg-[var(--color-background-tertiary)]">
                    <td className="px-4 py-3">
                      <div className="w-12 h-12 rounded-lg overflow-hidden bg-[var(--color-background-secondary)] flex-shrink-0 border-[0.5px] border-[var(--color-border-tertiary)]">
                        {img ? (
                          // eslint-disable-next-line @next/next/no-img-element
                          <img 
                            src={img} 
                            alt={product.name} 
                            className="w-full h-full object-cover"
                            crossOrigin="anonymous"
                            referrerPolicy="no-referrer"
                            loading="lazy"
                          />
                        ) : (
                          <div className="w-full h-full flex items-center justify-center text-xl">🏥</div>
                        )}
                      </div>
                    </td>
                    <td className="px-4 py-3 text-xs font-mono text-[var(--color-text-secondary)]">{product.sku}</td>
                    <td className="px-4 py-3 text-xs font-medium">{product.name}</td>
                    <td className="px-4 py-3 text-xs">{categoryName || '—'}</td>
                    <td className="px-4 py-3 text-xs font-semibold font-[family-name:var(--font-plus-jakarta)]">{product.stock}</td>
                    <td className="px-4 py-3 text-xs font-semibold font-[family-name:var(--font-plus-jakarta)]">
                      ৳{(product.price || 0).toLocaleString()}
                    </td>
                    <td className="px-4 py-3">
                      <span className={`text-xs px-2 py-[3px] rounded font-medium ${stockStatus.color}`}>
                        {stockStatus.label}
                      </span>
                    </td>
                    <td className="px-4 py-3">
                      <button
                        onClick={() => handleEditOpen(product)}
                        className="text-xs text-brand-teal font-medium hover:underline mr-3"
                      >
                        Edit
                      </button>
                      <button
                        onClick={() => handleDelete(product._id)}
                        className="text-xs text-danger font-medium hover:underline"
                      >
                        Delete
                      </button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        )}
      </div>

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="p-4 flex items-center justify-between border-t-[0.5px] border-[var(--color-border-tertiary)]">
          <button
            onClick={() => setPage(p => Math.max(1, p - 1))}
            disabled={page === 1}
            className="min-h-[44px] text-xs px-4 border-[0.5px] border-[var(--color-border-secondary)] rounded-lg disabled:opacity-40 hover:bg-[var(--color-background-secondary)] transition-colors"
          >
            ← Prev
          </button>
          <span className="text-xs text-[var(--color-text-secondary)]">Page {page} of {totalPages}</span>
          <button
            onClick={() => setPage(p => Math.min(totalPages, p + 1))}
            disabled={page === totalPages}
            className="min-h-[44px] text-xs px-4 border-[0.5px] border-[var(--color-border-secondary)] rounded-lg disabled:opacity-40 hover:bg-[var(--color-background-secondary)] transition-colors"
          >
            Next →
          </button>
        </div>
      )}
    </div>
  );
}
