/**
 * Product Pages Sitemap for MedCore BD
 * 
 * Serves a static sitemap file generated at build time.
 * The sitemap is generated by scripts/generate-sitemap.js during npm run build.
 * 
 * Benefits:
 * - No runtime API calls or timeouts
 * - Always reliable and fast
 * - Updates on every deployment
 * 
 * Route: /sitemap-products.xml
 */

import fs from 'fs';
import path from 'path';

export async function GET() {
  try {
    // Read the static sitemap file generated at build time
    const sitemapPath = path.join(process.cwd(), 'public', 'sitemap-products-static.xml');
    
    if (fs.existsSync(sitemapPath)) {
      const sitemap = fs.readFileSync(sitemapPath, 'utf-8');
      
      return new Response(sitemap, {
        headers: {
          'Content-Type': 'application/xml',
          'Cache-Control': 'public, max-age=3600, s-maxage=3600', // 1 hour cache
        },
      });
    } else {
      // Fallback if file doesn't exist (shouldn't happen in production)
      console.error('[sitemap-products] Static sitemap file not found:', sitemapPath);
      
      const fallbackSitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <!-- Static sitemap file not found. Run 'npm run build' to generate. -->
</urlset>`;

      return new Response(fallbackSitemap, {
        headers: {
          'Content-Type': 'application/xml',
          'Cache-Control': 'public, max-age=60, s-maxage=60', // 1 minute cache
        },
      });
    }
  } catch (error) {
    console.error('[sitemap-products] Error reading static sitemap:', error.message);
    
    const errorSitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <!-- Error reading static sitemap file. -->
</urlset>`;

    return new Response(errorSitemap, {
      headers: {
        'Content-Type': 'application/xml',
        'Cache-Control': 'public, max-age=60, s-maxage=60',
      },
    });
  }
}
