/**
 * Product Pages Sitemap for MediportBD
 * 
 * Redirects to static sitemap file generated at build time.
 * The sitemap is generated by scripts/generate-sitemap.js during npm run build.
 * 
 * Benefits:
 * - No runtime API calls or timeouts
 * - Always reliable and fast (serves static file)
 * - Updates on every deployment
 * 
 * Route: /sitemap-products.xml → redirects to /sitemap-products-static.xml
 */

import { redirect } from 'next/navigation';

export async function GET() {
  // Redirect to the static sitemap file in public directory
  // Next.js serves files from public/ at the root URL
  redirect('/sitemap-products-static.xml');
}
